# Generated by Django 3.0.14 on 2023-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('cardnumber', models.IntegerField()),
                ('expiration', models.CharField(max_length=400)),
                ('cvv', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
